### Create Person
POST http://localhost:8081/person
Content-Type: application/json
X-Action-By: 796e62b1-b093-4a38-912d-26c1c82d763c

{
    "national_id_number": "0924979011",
    "first_name": "reza",
    "last_name": "Doe",
    "family_info_id": 1,
    "physical_info_id": 1,
    "contact_info_id": 1,
    "skills_id": 1,
    "birth_date": "1990-01-01",
    "religion_id": 1,
    "person_type_id": 1,
    "military_details_id": 1
}

### Get Person by ID
GET http://localhost:8081/person/0924979011
Content-Type: application/json
