### Login Request (Public Endpoint)

POST http://localhost:8080/api/personinfo/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin123"
}

###

### Get Static Tables (Protected Endpoint)

GET http://localhost:8080/api/personinfo/static/static-tables
Content-Type: application/json
X-Action-By: 083308ac-3c6b-4c5a-a1f5-6dfc63d4d63f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6ImU1ZGE4NDU2LTM4NGUtNGY5YS04ZTdmLWJmMmE2ZTdkZjM4YyIsImV4cCI6MTc0ODU5MDY1MSwicm9sZSI6MX0.JsS6yGjmTdVIvQbI5VWWFdYTqzIPM2ostuYSiGjxHPo
###

### Create Full Person (Protected Endpoint)
POST http://localhost:8080/api/personinfo/dynamic/persons/full
Content-Type: application/json
X-Action-By: a93506dc-e9b0-466b-b8ed-0a55b56eee97
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjgxNTNlOTEyLTk1YzAtNDlkNi05ZDI5LTY1Mjk3YWY2ZDIwNyIsImV4cCI6MTc0ODUwNjI5NSwicm9sZSI6MX0.a4lbEMy0mozcHsWLo7H4R67aQr-pYsHrS1bhD9oSags

{
  "national_id_number": "012347789",
  "first_name": "John",
  "last_name": "Doe",
  "birth_date": "1990-01-01",
  "family_info": {
    "father_details": "{\"name\": \"John Sr.\", \"occupation\": \"Engineer\"}",
    "mother_details": "{\"name\": \"Mary\", \"occupation\": \"Teacher\"}",
    "childs_details": "[]",
    "husband_details": "{}"
  },
  "contact_info": {
    "address": "123 Main St, City, Country",
    "phone_number": "+1234567890",
    "emergency_phone_number": "+0987654321",
    "landline_phone": "123-456-7890",
    "email_address": "john.doe@example.com",
    "social_media": "{\"twitter\": \"@johndoe\", \"linkedin\": \"johndoe\"}"
  },
  "skills": {
    "education": {
      "education_level_id": 3,
      "description": "BSc in Computer Science",
      "university": "Example University",
      "start_date": 1514764800,
      "end_date": 1625097600
    },
    "languages": "[\"English\", \"Spanish\"]",
    "skills_description": "Proficient in Go, Python, and SQL",
    "certificates": "AWS Certified Developer, PMP"
  },
  "physical_info": {
    "blood_group_id": 1,
    "height": 175,
    "weight": 70
  },
  "religion": {
    "religion_id": 1
  },
  "person_type": {
    "person_type_id": 1
  },
  "military_details": {
    "rank_id": 1,
    "service_start_date": 1514764800,
    "service_dispatch_date": 1625097600,
    "service_unit": 101,
    "battalion_unit": 202,
    "company_unit": 303
  }
}