@baseUrl = http://localhost:8081
@actionBy = b6037cfb-9434-498f-a139-d925810257a3

@adminId = b6037cfb-9434-498f-a139-d925810257a3

### Create Credentials - Success
POST {{baseUrl}}/credentials
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "admin_id": "{{adminId}}",
    "static_token": "static123",
    "dynamic_token": "dynamic123"
}

### Create Credentials - Invalid Admin ID
POST {{baseUrl}}/credentials
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "admin_id": "invalid-uuid",
    "static_token": "static123",
    "dynamic_token": "dynamic123"
}

### Create Credentials - Missing X-Action-By
POST {{baseUrl}}/credentials
Content-Type: application/json


{
    "admin_id": "{{adminId}}",
    "static_token": "static123",
    "dynamic_token": "dynamic123"
}

### Get Credentials by Admin ID - Success
GET {{baseUrl}}/credentials/{{adminId}}


### Get Credentials by Admin ID - Invalid ID
GET {{baseUrl}}/credentials/invalid-uuid


### Get All Credentials - Success
GET {{baseUrl}}/credentials


### Get Soft Deleted Credentials - Success
GET {{baseUrl}}/credentials/softdeleted


### Update Credentials - Success
PUT {{baseUrl}}/credentials/{{adminId}}
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "static_token": "newstatic456"
}

### Update Credentials - Invalid ID
PUT {{baseUrl}}/credentials/invalid-uuid
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "static_token": "newstatic456"
}

### Update Dynamic Token - Success
PUT {{baseUrl}}/credentials/dynamic_token/{{adminId}}
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "dynamic_token": "newdynamic789"
}

### Update Dynamic Token - Missing X-Action-By
PUT {{baseUrl}}/credentials/dynamic_token/{{adminId}}
Content-Type: application/json


{
    "dynamic_token": "newdynamic789"
}

### Delete Credentials - Success
DELETE {{baseUrl}}/credentials/{{adminId}}
X-Action-By: {{actionBy}}


### Delete Credentials Hard - Success
DELETE {{baseUrl}}/credentials/hard/{{adminId}}
X-Action-By: {{actionBy}}


### Get Static Token by Admin ID - Success
GET {{baseUrl}}/credentials/static_token/{{adminId}}


### Get Dynamic Token by Admin ID - Success
GET {{baseUrl}}/credentials/dynamic_token/{{adminId}}
