@baseUrl = http://localhost:8081
@actionBy = 796e62b1-b093-4a38-912d-876c2d763c
@token = <jwt_token>
@militaryId = 1

### Create Military Details - Success
POST {{baseUrl}}/militarydetails
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "rank_id": 1,
    "service_start_date": 1609459200,
    "service_dispatch_date": 1640995200,
    "service_unit": 1,
    "battalion_unit": 1,
    "company_unit": 1
}

### Create Military Details - Invalid Input
POST {{baseUrl}}/militarydetails
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "rank_id": 1
}

### Get Military Details by ID - Success
GET {{baseUrl}}/militarydetails/{{militaryId}}
Authorization: Bearer {{token}}

### Get All Military Details - Success
GET {{baseUrl}}/militarydetails
Authorization: Bearer {{token}}

### Delete Military Details - Success
DELETE {{baseUrl}}/militarydetails/{{militaryId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}