@baseUrl = https://api.sorooshdavoodi.ir/api/personinfo/static
@actionBy = 796e62b1-b093-4a38-912d-876c2d763c
@token = <jwt_token>
@nationalId = 123456789012

### Create Person - Success
POST {{baseUrl}}/person
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "national_id_number": "{{nationalId}}",
    "first_name": "John",
    "last_name": "Doe",
    "family_info_id": 1,
    "physical_info_id": 1,
    "contact_info_id": 1,
    "skills_id": 1,
    "birth_date": "1990-01-01",
    "religion_id": 1,
    "person_type_id": 1,
    "military_details_id": 1
}

### Create Person - Invalid Birth Date
POST {{baseUrl}}/persons
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "national_id_number": "{{nationalId}}",
    "first_name": "John",
    "last_name": "Doe",
    "family_info_id": 1,
    "physical_info_id": 1,
    "contact_info_id": 1,
    "skills_id": 1,
    "birth_date": "invalid",
    "religion_id": 1,
    "person_type_id": 1,
    "military_details_id": 1
}

### Get Person by ID - Success
GET http://localhost:8080/api/personinfo/static/person/019333789
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6ImVkODZjZjAyLWEyZjMtNDU2ZS05ZjI1LWQzN2Q5ZGUzODNiYiIsImV4cCI6MTc0ODYwMDEwOSwicm9sZSI6MX0.jbXVdwwap-0HLh36XyM5fR1sZ18yStSWYyYvCC3-aEs

### Get All Persons - Success
GET http://localhost:8080/api/personinfo/static/persons
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6ImVkODZjZjAyLWEyZjMtNDU2ZS05ZjI1LWQzN2Q5ZGUzODNiYiIsImV4cCI6MTc0ODYwMDEwOSwicm9sZSI6MX0.jbXVdwwap-0HLh36XyM5fR1sZ18yStSWYyYvCC3-aEs


### Update Person - Success
PUT {{baseUrl}}/person/{{nationalId}}
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "first_name": "Jane"
}

### Update Contact Info - Success
PUT {{baseUrl}}/person/{{nationalId}}/contactinfo
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "contact_info_id": 2
}

### Update Military Details - Success
PUT {{baseUrl}}/person/{{nationalId}}/militarydetails
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "military_details_id": 2
}

### Delete Person - Success
DELETE {{baseUrl}}/person/{{nationalId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

### Delete Person Hard - Success
DELETE {{baseUrl}}/person/hard/{{nationalId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

### Search Persons by Name - Success
GET {{baseUrl}}/person/search?first_name=John&last_name=Doe
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

### Filter Persons by Person Type - Success
GET {{baseUrl}}/person/filter?person_type_id=1
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}