@baseUrl = http://localhost:8081
@actionBy = 796e62b1-b093-4a38-912d-876c2d763c
@token = <jwt_token>
@physicalId = 1

### Create Physical Info - Success
POST {{baseUrl}}/physicalinfo
Content-Type: application/json
X-Action-By: 083308ac-3c6b-4c5a-a1f5-6dfc63d4d63f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjA4MzMwOGFjLTNjNmItNGM1YS1hMWY1LTZkZmM2M2Q0ZDYzZiIsImV4cCI6MTc0ODQ5OTk0NSwicm9sZSI6MX0.mJkKzjEb7yPgmvV_JizORl7ZaqL6dmbq9c8mpr_Jh38


{
    "height": 175,
    "weight": 70,
    "eye_color": "Blue",
    "blood_group_id": 1,
    "gender_id": 1,
    "physical_status_id": 1
}

### Create Physical Info - Invalid Input
POST {{baseUrl}}/physicalinfo
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjA4MzMwOGFjLTNjNmItNGM1YS1hMWY1LTZkZmM2M2Q0ZDYzZiIsImV4cCI6MTc0ODUwMDIxMiwicm9sZSI6MX0.0Z_grjvL_KagNpMsHsj_TJYbFzQDoUg0OKs51MKsrBQ

{
    "height": 175
}

### Get Physical Info by ID - Success
GET {{baseUrl}}/physicalinfo/{{physicalId}}
X-Action-By: 083308ac-3c6b-4c5a-a1f5-6dfc63d4d63f

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjA4MzMwOGFjLTNjNmItNGM1YS1hMWY1LTZkZmM2M2Q0ZDYzZiIsImV4cCI6MTc0ODUwMDIxMiwicm9sZSI6MX0.0Z_grjvL_KagNpMsHsj_TJYbFzQDoUg0OKs51MKsrBQ

### Get All Physical Infos - Success
GET {{baseUrl}}/physicalinfo
X-Action-By: 083308ac-3c6b-4c5a-a1f5-6dfc63d4d63f

Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbl9pZCI6IjA4MzMwOGFjLTNjNmItNGM1YS1hMWY1LTZkZmM2M2Q0ZDYzZiIsImV4cCI6MTc0ODUwMDIxMiwicm9sZSI6MX0.0Z_grjvL_KagNpMsHsj_TJYbFzQDoUg0OKs51MKsrBQ


### Update Physical Info - Success
PUT {{baseUrl}}/physicalinfo/{{physicalId}}
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "height": 180
}

### Delete Physical Info - Success
DELETE {{baseUrl}}/physicalinfo/{{physicalId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}