@baseUrl = http://localhost:8081
@actionBy = 796e62b1-b093-4a38-912d-876c2d763c
@token = <jwt_token>
@roleId = 1
@typeName = Admin

### Create Role - Success
POST {{baseUrl}}/role
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "type_name": "{{typeName}}"
}

### Create Role - Invalid Input
POST {{baseUrl}}/role
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{}

### Get Role by ID - Success
GET {{baseUrl}}/role/{{roleId}}
Authorization: Bearer {{token}}

### Get Role by Type - Success
GET {{baseUrl}}/role/type/{{typeName}}
Authorization: Bearer {{token}}

### Get All Roles - Success
GET {{baseUrl}}/role
Authorization: Bearer {{token}}

### Update Role - Success
PUT {{baseUrl}}/role/{{roleId}}
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "type_name": "SuperAdmin"
}

### Delete Role - Success
DELETE {{baseUrl}}/role/{{roleId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}