version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    depends_on:
      migrator:
        condition: service_completed_successfully
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      APP_HOST: 0.0.0.0
      APP_PORT: 5000
      DB_NAME: military_db
      JWT_SECRET: SOMESECRETFORJWT_lkdjasdasdjl
      IS_TEST: true
    ports:
      - "5000:5000"

  db:
    image: postgres:15
    container_name: military-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: military_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8885:80"
    depends_on:
      - db

  migrator:
    image: migrate/migrate
    container_name: db-migrator
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://postgres:postgres@db:5432/military_db?sslmode=disable",
        "up",
      ]
    restart: "on-failure"

volumes:
  pgdata:
