version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: military_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  databaseservice:
    build:
      context: .
      dockerfile: Dockerfile.databaseservice
    ports:
      - "8080:8080"
    environment:
      - APP_NAME=databaseservice
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=securepassword
      - DB_NAME=military_db
      - DB_PORT=5432
      - LOG_LEVEL=info
      - LOG_FORMAT=text
      - STATIC_SECRET=static-secret-key
      - DYNAMIC_SECRET=dynamic-secret-key
      - DATABASE_URL=postgres://admin:securepassword@postgres:5432/military_db?sslmode=disable
    depends_on:
      - postgres
    networks:
      - app-network
  personinfoservice:
    build:
      context: .
      dockerfile: Dockerfile.personinfoservice
    ports:
      - "8081:8081"
    environment:
      - APP_NAME=personinfoservice
      - APP_HOST=0.0.0.0
      - APP_PORT=8081
      - DB_SERVICE_URL=http://databaseservice:8080
      - LOG_LEVEL=info
      - LOG_FORMAT=text
    depends_on:
      - databaseservice
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge