@baseUrl = http://localhost:8081
@actionBy = 5d2f044a-9d3e-4661-90d2-57ff7c236303
@adminId = b6037cfb-9434-498f-a139-d925810257a3

### Create Admin - Success
POST {{baseUrl}}/admin
Content-Type: application/json
X-Action-By: {{actionBy}}

{
    "national_id_number": "123456789012",
    "user_name": "testadmin",
    "password": "SecurePass123",
    "role_id": 1,
    "credentials_id": 1
}

### Create Admin - Invalid Input (Missing Fields)
POST {{baseUrl}}/admin
Content-Type: application/json
X-Action-By: {{actionBy}}
{
    "national_id_number": "123456789012",
    "user_name": "testadmin"
}

### Create Admin - Missing X-Action-By
POST {{baseUrl}}/admin
Content-Type: application/json

{
    "national_id_number": "123456789012",
    "user_name": "testadmin",
    "password": "SecurePass123",
    "role_id": 1,
    "credentials_id": 1
}

### Get Admin by ID - Success
GET {{baseUrl}}/admin/{{"adminId"}}


### Get Admin by ID - Invalid ID
GET {{baseUrl}}/admin/invalid-uuid

### Get Admin by Username - Success
GET {{baseUrl}}/admin/username/testadmin


### Get Admin by Username - Not Found
GET {{baseUrl}}/admin/username/nonexistent

### Get All Admins - Success
GET {{baseUrl}}/admin


### Update Admin - Success
PUT {{baseUrl}}/admin/{{adminId}}
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "user_name": "updatedadmin"
}

### Update Admin - Invalid ID
PUT {{baseUrl}}/admin/invalid-uuid
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "user_name": "updatedadmin"
}

### Update Admin Password - Success
PUT {{baseUrl}}/admin/password/{{adminId}}
Content-Type: application/json
X-Action-By: {{actionBy}}


{
    "password": "NewPass456"
}

### Update Admin Password - Missing X-Action-By
PUT {{baseUrl}}/admin/password/{{adminId}}
Content-Type: application/json

{
    "password": "NewPass456"
}

### Delete Admin - Success
DELETE {{baseUrl}}/admin/{{adminId}}
X-Action-By: {{actionBy}}


### Delete Admin - Invalid ID
DELETE {{baseUrl}}/admin/invalid-uuid
X-Action-By: {{actionBy}}


### Soft Delete Admin - Success
DELETE {{baseUrl}}/admin/soft/{{adminId}}
X-Action-By: {{actionBy}}
