@baseUrl = http://localhost:8081
@actionBy = 796e62b1-b093-4a38-912d-876c2d763c
@token = <jwt_token>
@educationId = 1

### Create Education - Success
POST {{baseUrl}}/education
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "education_level_id": 1,
    "field_of_study": 1,
    "description": "Computer Science",
    "university": "Test University",
    "start_date": 1609459200,
    "end_date": 1640995200
}

### Create Education - Invalid Input
POST {{baseUrl}}/education
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "education_level_id": 1
}

### Get Education by ID - Success
GET {{baseUrl}}/education/{{educationId}}
Authorization: Bearer {{token}}

### Get Education by ID - Invalid ID
GET {{baseUrl}}/education/invalid
Authorization: Bearer {{token}}

### Get All Educations - Success
GET {{baseUrl}}/education
Authorization: Bearer {{token}}

### Update Education - Success
PUT {{baseUrl}}/education/{{educationId}}
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "description": "Updated Description"
}

### Delete Education - Success
DELETE {{baseUrl}}/education/{{educationId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

### Search Educations by University - Success
GET {{baseUrl}}/education/search?university=Test%20University
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}