@baseUrl = http://localhost:8081
@actionBy = 796e62b1-b093-4a38-912d-876c2d763c
@token = <jwt_token>
@skillsId = 1
@educationId = 1

### Create Skills - Success
POST {{baseUrl}}/skills
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "education_id": {{educationId}},
    "languages": "English, Spanish",
    "skills_description": "Programming, Data Analysis",
    "certificates": "AWS Certified"
}

### Create Skills - Invalid Input
POST {{baseUrl}}/skills
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "education_id": {{educationId}}
}

### Get Skills by ID - Success
GET {{baseUrl}}/skills/{{skillsId}}
Authorization: Bearer {{token}}

### Get Skills by Education ID - Success
GET {{baseUrl}}/skills/education/{{educationId}}
Authorization: Bearer {{token}}

### Get All Skills - Success
GET {{baseUrl}}/skills
Authorization: Bearer {{token}}

### Update Skills - Success
PUT {{baseUrl}}/skills/{{skillsId}}
Content-Type: application/json
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}

{
    "languages": "English, French"
}

### Delete Skills - Success
DELETE {{baseUrl}}/skills/{{skillsId}}
X-Action-By: {{actionBy}}
Authorization: Bearer {{token}}